[2025-08-16 23:00:11,916] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.drop_table_create_orders manual__2025-08-16T23:00:08.759833+00:00 [queued]>
[2025-08-16 23:00:11,927] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.drop_table_create_orders manual__2025-08-16T23:00:08.759833+00:00 [queued]>
[2025-08-16 23:00:11,928] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 23:00:11,930] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-16 23:00:11,936] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 23:00:11,959] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): drop_table_create_orders> on 2025-08-16 23:00:08.759833+00:00
[2025-08-16 23:00:11,971] {standard_task_runner.py:52} INFO - Started process 134 to run task
[2025-08-16 23:00:11,982] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '1_load_initial_data', 'drop_table_create_orders', 'manual__2025-08-16T23:00:08.759833+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/initialise_data.py', '--cfg-path', '/tmp/tmpfu1yiz4e', '--error-file', '/tmp/tmpmn2yckfi']
[2025-08-16 23:00:11,992] {standard_task_runner.py:80} INFO - Job 3: Subtask drop_table_create_orders
[2025-08-16 23:00:12,303] {task_command.py:369} INFO - Running <TaskInstance: 1_load_initial_data.drop_table_create_orders manual__2025-08-16T23:00:08.759833+00:00 [running]> on host 03b58f608368
[2025-08-16 23:00:12,491] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=1_load_initial_data
AIRFLOW_CTX_TASK_ID=drop_table_create_orders
AIRFLOW_CTX_EXECUTION_DATE=2025-08-16T23:00:08.759833+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-16T23:00:08.759833+00:00
[2025-08-16 23:00:12,498] {sql.py:262} INFO - Executing: DROP TABLE IF EXISTS dbt_raw_data.orders;
[2025-08-16 23:00:12,528] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 23:00:12,575] {logging_mixin.py:115} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/connection.py:339 DeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
[2025-08-16 23:00:12,601] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 23:00:12,610] {sql.py:375} INFO - Running statement: DROP TABLE IF EXISTS dbt_raw_data.orders;, parameters: None
[2025-08-16 23:00:12,632] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=1_load_initial_data, task_id=drop_table_create_orders, execution_date=20250816T230008, start_date=20250816T230011, end_date=20250816T230012
[2025-08-16 23:00:12,680] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-16 23:00:12,742] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
