[2025-08-16 23:00:16,534] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.create_customers manual__2025-08-16T23:00:08.759833+00:00 [queued]>
[2025-08-16 23:00:16,542] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.create_customers manual__2025-08-16T23:00:08.759833+00:00 [queued]>
[2025-08-16 23:00:16,543] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 23:00:16,544] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-16 23:00:16,545] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 23:00:16,553] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_customers> on 2025-08-16 23:00:08.759833+00:00
[2025-08-16 23:00:16,558] {standard_task_runner.py:52} INFO - Started process 149 to run task
[2025-08-16 23:00:16,564] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '1_load_initial_data', 'create_customers', 'manual__2025-08-16T23:00:08.759833+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/initialise_data.py', '--cfg-path', '/tmp/tmpd__6n1pv', '--error-file', '/tmp/tmp8b0uv92x']
[2025-08-16 23:00:16,566] {standard_task_runner.py:80} INFO - Job 13: Subtask create_customers
[2025-08-16 23:00:16,647] {task_command.py:369} INFO - Running <TaskInstance: 1_load_initial_data.create_customers manual__2025-08-16T23:00:08.759833+00:00 [running]> on host 03b58f608368
[2025-08-16 23:00:16,736] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=1_load_initial_data
AIRFLOW_CTX_TASK_ID=create_customers
AIRFLOW_CTX_EXECUTION_DATE=2025-08-16T23:00:08.759833+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-16T23:00:08.759833+00:00
[2025-08-16 23:00:16,738] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS dbt_raw_data.customers (
        customer_id INT PRIMARY KEY,
        email_address VARCHAR(255),
        name VARCHAR(128),
        business_type_id INT,
        site_code VARCHAR(13),
        archived BOOLEAN,
        is_key_account BOOLEAN,
        date_updated TIMESTAMP,
        date_created TIMESTAMP
    );
    
[2025-08-16 23:00:16,757] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 23:00:16,779] {logging_mixin.py:115} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/connection.py:339 DeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
[2025-08-16 23:00:16,806] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 23:00:16,814] {sql.py:375} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS dbt_raw_data.customers (
        customer_id INT PRIMARY KEY,
        email_address VARCHAR(255),
        name VARCHAR(128),
        business_type_id INT,
        site_code VARCHAR(13),
        archived BOOLEAN,
        is_key_account BOOLEAN,
        date_updated TIMESTAMP,
        date_created TIMESTAMP
    );
    , parameters: None
[2025-08-16 23:00:16,845] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=1_load_initial_data, task_id=create_customers, execution_date=20250816T230008, start_date=20250816T230016, end_date=20250816T230016
[2025-08-16 23:00:16,897] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-16 23:00:16,940] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
