[2025-08-16 23:00:16,560] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.create_dim_fecha manual__2025-08-16T23:00:08.759833+00:00 [queued]>
[2025-08-16 23:00:16,569] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.create_dim_fecha manual__2025-08-16T23:00:08.759833+00:00 [queued]>
[2025-08-16 23:00:16,571] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 23:00:16,572] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-16 23:00:16,573] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 23:00:16,586] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_dim_fecha> on 2025-08-16 23:00:08.759833+00:00
[2025-08-16 23:00:16,594] {standard_task_runner.py:52} INFO - Started process 150 to run task
[2025-08-16 23:00:16,599] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '1_load_initial_data', 'create_dim_fecha', 'manual__2025-08-16T23:00:08.759833+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/initialise_data.py', '--cfg-path', '/tmp/tmpo1u8vy5w', '--error-file', '/tmp/tmpl2n5i74w']
[2025-08-16 23:00:16,601] {standard_task_runner.py:80} INFO - Job 11: Subtask create_dim_fecha
[2025-08-16 23:00:16,685] {task_command.py:369} INFO - Running <TaskInstance: 1_load_initial_data.create_dim_fecha manual__2025-08-16T23:00:08.759833+00:00 [running]> on host 03b58f608368
[2025-08-16 23:00:16,769] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=1_load_initial_data
AIRFLOW_CTX_TASK_ID=create_dim_fecha
AIRFLOW_CTX_EXECUTION_DATE=2025-08-16T23:00:08.759833+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-16T23:00:08.759833+00:00
[2025-08-16 23:00:16,772] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS dbt_raw_data.dim_fecha (
        fecha_id SERIAL PRIMARY KEY,
        fecha DATE NOT NULL,
        anio SMALLINT NOT NULL,
        mes SMALLINT NOT NULL,
        dia SMALLINT NOT NULL,
        dia_semana SMALLINT NOT NULL,
        nombre_dia_semana VARCHAR(20) NOT NULL,
        nombre_mes VARCHAR(20) NOT NULL,
        trimestre SMALLINT NOT NULL,
        anio_semana SMALLINT NOT NULL,
        es_fin_semana BOOLEAN NOT NULL
    );
    
[2025-08-16 23:00:16,792] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 23:00:16,821] {logging_mixin.py:115} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/connection.py:339 DeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
[2025-08-16 23:00:16,840] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 23:00:16,850] {sql.py:375} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS dbt_raw_data.dim_fecha (
        fecha_id SERIAL PRIMARY KEY,
        fecha DATE NOT NULL,
        anio SMALLINT NOT NULL,
        mes SMALLINT NOT NULL,
        dia SMALLINT NOT NULL,
        dia_semana SMALLINT NOT NULL,
        nombre_dia_semana VARCHAR(20) NOT NULL,
        nombre_mes VARCHAR(20) NOT NULL,
        trimestre SMALLINT NOT NULL,
        anio_semana SMALLINT NOT NULL,
        es_fin_semana BOOLEAN NOT NULL
    );
    , parameters: None
[2025-08-16 23:00:16,872] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=1_load_initial_data, task_id=create_dim_fecha, execution_date=20250816T230008, start_date=20250816T230016, end_date=20250816T230016
[2025-08-16 23:00:16,898] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-16 23:00:16,956] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
