[2025-08-16 21:25:28,110] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.create_schema manual__2025-08-16T21:25:27.221750+00:00 [queued]>
[2025-08-16 21:25:28,121] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.create_schema manual__2025-08-16T21:25:27.221750+00:00 [queued]>
[2025-08-16 21:25:28,123] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 21:25:28,124] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-16 21:25:28,125] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 21:25:28,136] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_schema> on 2025-08-16 21:25:27.221750+00:00
[2025-08-16 21:25:28,146] {standard_task_runner.py:52} INFO - Started process 315 to run task
[2025-08-16 21:25:28,168] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '1_load_initial_data', 'create_schema', 'manual__2025-08-16T21:25:27.221750+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/initialise_data.py', '--cfg-path', '/tmp/tmprswrn6i9', '--error-file', '/tmp/tmpaofehnq2']
[2025-08-16 21:25:28,173] {standard_task_runner.py:80} INFO - Job 2: Subtask create_schema
[2025-08-16 21:25:28,265] {task_command.py:369} INFO - Running <TaskInstance: 1_load_initial_data.create_schema manual__2025-08-16T21:25:27.221750+00:00 [running]> on host 6a6e6aafe640
[2025-08-16 21:25:28,340] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=1_load_initial_data
AIRFLOW_CTX_TASK_ID=create_schema
AIRFLOW_CTX_EXECUTION_DATE=2025-08-16T21:25:27.221750+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-16T21:25:27.221750+00:00
[2025-08-16 21:25:28,342] {sql.py:262} INFO - Executing: CREATE SCHEMA IF NOT EXISTS dbt_raw_data;
[2025-08-16 21:25:28,359] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 21:25:28,426] {logging_mixin.py:115} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/connection.py:339 DeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
[2025-08-16 21:25:28,439] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 21:25:28,477] {sql.py:375} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS dbt_raw_data;, parameters: None
[2025-08-16 21:25:28,500] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=1_load_initial_data, task_id=create_schema, execution_date=20250816T212527, start_date=20250816T212528, end_date=20250816T212528
[2025-08-16 21:25:28,546] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-16 21:25:28,586] {local_task_job.py:273} INFO - 5 downstream tasks scheduled from follow-on schedule check
